name: Deploy and Run Application

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    # Step 3: Run commands on AWS VPS
    - name: Deploy and Run App on VPS
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<your-vps-ip> << 'EOF'
          cd /home/ubuntu/emege-x-admin-portal
          git pull origin main
          npm install
          nohup npm run dev &> app.log &
          echo "Application is running in the background. Logs are in app.log."
        EOF
